variables:
  DISTRIBUTION_VER: "buster"
  CI_APT_PREFIX: "k8s-1.20"

image: docker.git.sos.ethz.ch/isg/debian-ci-base-int:$DISTRIBUTION_VER

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - apt update
    - apt install -y go-md2man golang-any golang-1.15
    - apt install -y -t buster-backports debhelper-compat
    - export PATH=/usr/lib/go-1.15/bin:$PATH 
    - export GOROOT=/usr/lib/go-1.15
    - export GOPATH=/root/go
  script:
    - gbp buildpackage --git-ignore-branch -b -us -uc
    - mv ../*.deb . # GitLab can't copy from the parent directory...
  artifacts:
    name: packets
    expire_in: 3 months
    paths:
      - '*.deb'

deploy_to_apt:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploying package to $CI_APT_PREFIX prefix and $DISTRIBUTION_VER version"
    - sudo -u repo aptly repo add $CI_APT_PREFIX *.deb
    - sudo -u repo aptly publish update $DISTRIBUTION_VER $CI_APT_PREFIX
  only:
    - tags
  tags:
    - apt
